trigger:
  branches:
    include:
      - main

stages:
- stage: SyncToGitHub
  displayName: 'Sync Azure DevOps Repo to GitHub'
  jobs:
  - job: MirrorJob
    displayName: 'Mirror to GitHub'
    pool:
      name: Default
    steps:
    - checkout: self
    - script: |
        git config --global user.email "deepp.knowledge@gmail.com"
        git config --global user.name "DeepKnowledge1"

        git remote remove github || echo remote not found
        git remote add github https://$(GITHUB_PAT)@github.com/DeepKnowledge1/$(Build.Repository.Name).git

        git push github HEAD:main --force
      displayName: 'Push to GitHub'




# git remote add devops https://deepknowledge@dev.azure.com/deepknowledge/mlops-AnomaVision/_git/AnomaVision
# git branch -vv                                                                                                                         
#  git push --set-upstream devops main  




# git remote add devops https://deepknowledge@dev.azure.com/deepknowledge/mlops-AnomaVision/_git/industrial_anodet_mlops
# git branch -vv                                                                                                                         
# git push --set-upstream devops main  
