version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/application.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    formatter: simple
    level: DEBUG

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  industrial-mlops:
    level: DEBUG
    handlers: [console, file]
    propagate: no
