apiVersion: v1
kind: Service
metadata:
  name: anomavision-service
  labels:
    app: anomavision
spec:
  selector:
    app: anomavision
    type: FastAPI
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 8080  # Port on the container
  type: LoadBalancer   # Change to ClusterIP or NodePort if needed

