parameters: {}
jobs:
  - job: AssignAcrPullRole
    displayName: "Assign ACR Pull Role to ML Workspace Identity"
    steps:
      - task: AzureCLI@2
        displayName: "Grant ACR Pull Role"
        inputs:
          azureSubscription: mlops_anomaly_detection
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            $identity = az ml workspace show `
              --name $(WORKSPACE) `
              --resource-group $(RESOURCE_GROUP) `
              --query identity `
              --output json | ConvertFrom-Json

            $principalId = $identity.principal_id
            Write-Output "Principal ID: $principalId"

            $scope = az acr show --name $(ACR_NAME) --query id --output tsv

            az role assignment create `
              --assignee $principalId `
              --role AcrPull `
              --scope $scope
